#!/bin/bash

if [ ! -f "$1" ]; then
  echo "usage: tpott pcap-file-path"
  exit 1
fi

tshark -r $1 -V -T fields -e data.data |\
    sed '/^\s*$/d' |\
    sed 's/\([0-9a-fA-F][0-9a-fA-F]\)/#x\1/g' |\
    racket tpott.rkt |\
    # TODO this last passage is a hack, fix it
    sed '$ d'
